name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'daily.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
permissions:
  actions: write
env:
  MAINCACHE: ${{ runner.os }}-go-main
  DAILYCACHE: ${{ runner.os }}-go-daily
jobs:
  clear-cache:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Extension install
        run: gh extension install actions/gh-actions-cache
      - name: Remove Cache
        run: |
          gh actions-cache list -R $GITHUB_REPOSITORY \
          | xargs -I@ echo @ \
          | awk \
          -v dailycache=$DAILYCACHE \
          -v maincache=$MAINCACHE \
          '{if(index($1,maincache)!=0 || index($1,dailycache) != 0 ){print $1}}' \
          | xargs -I% gh actions-cache delete % -R $GITHUB_REPOSITORY --confirm
  build-main:
    runs-on: ubuntu-latest
    needs: clear-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        run: go build main.go
      - name: Add cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/main
          key: $MAINCACHE
  build-daily:
    runs-on: ubuntu-latest
    needs: clear-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        run: go build daily.go
      - name: Add cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/daily
          key: $DAILYCACHE
