name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'daily.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
permissions:
  actions: write
jobs:
  build-main:
    uses: tkmsaaaam/count-commits-js/.github/workflows/reusing_build.yml@main
    secrets:
      FILE_NAME: main
  build-daily:
    uses: tkmsaaaam/count-commits-js/.github/workflows/reusing_build.yml@main
    secrets:
      FILE_NAME: daily
