name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'daily.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
permissions:
  actions: write
jobs:
  build-main:
    uses: ./.github/workflows/reusing_build.yml
    with:
      FILE_NAME: main
      DIR_NAME: remover
  build-daily:
    uses: ./.github/workflows/reusing_build.yml
    with:
      FILE_NAME: daily
      DIR_NAME: summary
