name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'daily.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
permissions:
  actions: write
jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Cache Hit
        id: cache-hit
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/main
          key: ${{ runner.os }}-go-main-${{ hashFiles('**/go.sum', 'main.go') }}
      - name: Extension install
        if: steps.cache-hit.outputs.cache-hit != 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh extension install actions/gh-actions-cache
      - name: Remove old cache
        if: steps.cache-hit.outputs.cache-hit != 'false'
        env:
          MAINCACHE: ${{ runner.os }}-go-main
        run: |
          gh actions-cache list -R $GITHUB_REPOSITORY \
          | xargs -I@ echo @ \
          | awk \
          -v maincache=$MAINCACHE \
          '{if(index($1,maincache) != 0){print $1}}' \
          | xargs -I% gh actions-cache delete % -R $GITHUB_REPOSITORY --confirm
      - name: Setup Go
        if: steps.cache-hit.outputs.cache-hit != 'false'
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: setup cache
        if: steps.cache-hit.outputs.cache-hit != 'false'
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        if: steps.cache-hit.outputs.cache-hit != 'false'
        run: go build main.go
      - name: Add cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/main
          key: ${{ runner.os }}-go-main-${{ hashFiles('**/go.sum', 'main.go') }}
  build-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Cache Hit
        id: cache-hit
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/daily
          key: ${{ runner.os }}-go-daily-${{ hashFiles('**/go.sum', 'daily.go') }}
      - name: Extension install
        if: steps.cache-hit.outputs.cache-hit != 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh extension install actions/gh-actions-cache
      - name: Remove old cache
        if: steps.cache-hit.outputs.cache-hit != 'false'
        env:
          DAILYCACHE: ${{ runner.os }}-go-daily
        run: |
          gh actions-cache list -R $GITHUB_REPOSITORY \
          | xargs -I@ echo @ \
          | awk \
          -v dailycache=$DAILYCACHE \
          '{if(index($1,dailycache) != 0){print $1}}' \
          | xargs -I% gh actions-cache delete % -R $GITHUB_REPOSITORY --confirm
      - name: Setup Go
        if: steps.cache-hit.outputs.cache-hit != 'false'
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: setup cache
        if: steps.cache-hit.outputs.cache-hit != 'false'
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        if: steps.cache-hit.outputs.cache-hit != 'false'
        run: go build daily.go
      - name: Add cache
        if: steps.cache-hit.outputs.cache-hit != 'false'
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/daily
          key: ${{ runner.os }}-go-daily-${{ hashFiles('**/go.sum', 'daily.go') }}
