name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'daily.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
permissions:
  actions: write
jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Extension install
        run: gh extension install actions/gh-actions-cache
      - name: run
        run: gh actions-cache list -R $GITHUB_REPOSITORY | xargs -I@ echo @ | awk '{if(index($1,"Linux-go-daily")!=0 || index($1,"Linux-go-main") != 0 ){print $1}}' | xargs -I% gh actions-cache delete % -R $GITHUB_REPOSITORY
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        run: go build main.go
      - name: Add cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/main
          key: ${{ runner.os }}-go-main
  build-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        run: go build daily.go
      - name: Add cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/daily
          key: ${{ runner.os }}-go-daily
