name: Daily
permissions: {}
on:
  schedule:
    - cron: '13 13 * * *'
  workflow_run:
    workflows: [build]
    types: [completed]
jobs:
  script:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ github.event.schedule || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/daily
          key: ${{ runner.os }}-go-daily
      - name: Execute Post Daily report
        run: ${{ github.workspace }}/daily
        env:
          SLACK_OAUTH_BOT_TOKEN: ${{ secrets.SLACK_OAUTH_BOT_TOKEN }}
          SLACK_OAUTH_USER_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
