name: Daily
permissions: {}
on:
  schedule:
    - cron: '13 13 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types: [completed]
jobs:
  script:
    if: ${{ github.event_name == 'schedule' ||  github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusing_execute.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
    with:
      cacheName: daily
      fileName: main
      dirName: summary
