name: Go
permissions: {}
on:
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:
    inputs:
      days:
        type: number
        required: false
        description: 'days'
      timeout:
        type: number
        required: false
        description: 'timeout'
  workflow_run:
    workflows: [build]
    types: [completed]
jobs:
  script:
    runs-on: ubuntu-latest
    env:
      DAYS: ${{ github.event.inputs.days || 3 }}
      EXEC_FILEPATH: ${{ github.workspace }}/main
    timeout-minutes: ${{ github.event.inputs.timeout || 3 }}
    if: ${{ github.event_name == 'schedule' ||  github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: $EXEC_FILEPATH
          key: ${{ runner.os }}-go-main
      - name: Execute Delete messages
        run: $EXEC_FILEPATH $DAYS
        env:
          SLACK_OAUTH_BOT_TOKEN: ${{ secrets.SLACK_OAUTH_BOT_TOKEN }}
          SLACK_OAUTH_USER_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
