name: Go
permissions: {}
on:
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:
jobs:
  script:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: manage-slack
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ~/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/${{ env.REPO_NAME }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.TOKEN_FOR_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
