name: Go
permissions: {}
on:
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Run script
        run: go run main.go ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.TOKEN_FOR_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
        timeout-minutes: 1
