name: Go
permissions: {}
on:
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:
    inputs:
      days:
        type: number
        required: false
        description: 'days'
      timeout:
        type: number
        required: false
        description: 'timeout'
jobs:
  script:
    runs-on: ubuntu-latest
    env:
      DAYS: ${{ github.event.inputs.days || 3 }}
    timeout-minutes: ${{ github.event.inputs.timeout || 3 }}
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ~/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ github.event.repository.name }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.TOKEN_FOR_BOT }} ${{ secrets.SLACK_CHANNEL_ID }} $DAYS
