name: Go
permissions: {}
on:
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:
    inputs:
      days:
        type: number
        required: false
        description: 'days'
      timeout:
        type: number
        required: false
        description: 'timeout'
  workflow_run:
    workflows: [build]
    types: [completed]
jobs:
  script:
    if: ${{ github.event_name == 'schedule' ||  github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusing_execute.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
    with:
      days: ${{ github.event.inputs.days || 3 }}
      cacheName: main
      fileName: main
      timeout: ${{ github.event.inputs.timeout }}
      dirName: remover
