name: Go

on:
  schedule:
    - cron:  '13 * * * *'
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-go@latest
        with:
          go-version: ^1.18
      - name: Run script
        run : go run main.go ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.TOKEN_FOR_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
        timeout-minutes: 1
