name: ManageAction
permissions:
  actions: write
on:
  schedule:
    - cron: '12 12 1 * *'
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/manage_action.yml"
jobs:
  script:
    uses: tkmsaaaam/manage-slack/.github/workflows/manage_action.yml@main
