name: ManageAction
permissions:
  actions: write
on:
  schedule:
    - cron: '12 12 1 * *'
  workflow_dispatch:
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: manage actions
        run: |
          gh workflow list -a
          gh workflow list --repo $GITHUB_REPOSITORY | xargs -I@ echo @ | awk '{print $1}' | xargs -I% gh workflow disable % --repo $GITHUB_REPOSITORY
          gh workflow list -a --repo $GITHUB_REPOSITORY | xargs -I@ echo @ | awk '{print $1}' | xargs -I% gh workflow enable % --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
