name: Ruby

on:
  schedule:
    - cron:  '* 20 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 2.6.3
        bundler-cache: true
    - name: Run Script
      run: |
        bundle install --path vendor/bundle
        bundle exec ruby main.rb ${{ secrets.TOKEN_FOR_BOT }}
    - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02V3776R9S'
          payload: |
            {
              "text": ":GitHub: スクリプト実行結果: ${{ job.status }}\n\n${{ github.event.action.html_url || GitHub Actions }}"
            }
