name: workflow_run_notification
on:
  workflow_run:
    workflows: [Ruby, Run Script]
    types: [requested, completed]
jobs:
  on-requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == '' }}
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'C02V3776R9S'
          payload: |
            {
              "text": "タスク実行が開始されました"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TOKEN_FOR_BOT }}
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'C02V3776R9S'
          payload: |
            {
              "text": "GitHub タスク実行結果: <$GITHUB_EVENT_PATH | ${{ github.event.workflow_run.conclusion }}>"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TOKEN_FOR_BOT }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'C02V3776R9S'
          payload: |
            {
              "text": "GitHub タスク実行結果: <$GITHUB_EVENT_PATH | ${{ github.event.workflow_run.conclusion }}>"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TOKEN_FOR_BOT }}
